name: Vitor Baptista
description:
meta_description:

exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md", "Gemfile", "Gemfile.lock", "vendor", ".bundle"]

plugins: ["jekyll-paginate", "jekyll-sitemap"]

permalink: /:title
markdown: GFM
highlighter: rouge
logo: false
paginate: 15
baseurl: /
domain_name: 'https://vitorbaptista.com'
google_analytics: 'G-M0SK8H9FGZ'

# Social networks
github: vitorbaptista
twitter: vitorbaptista
email: vitor@vitorbaptista.com
linkedin: vitorbaptista
mastodon:
  instance: sigmoid.social
  handle: vitor

# Details for the RSS feed generator
url:            'https://vitorbaptista.com'
author:         'Vitor Baptista'
author_bio: 'Software engineer passioned for civic hacking, free software, data visualization, and all the ways of improving our world through technology.'
